language: php

php:
    - 7.0
    - hhvm

sudo: false

cache:
    directories:
        - $HOME/.composer/cache

matrix:
    fast_finish: true
    include:
        - php: 7.0
          env: SYMFONY_VERSION='2.8.*'
        - php: 7.0
          env: SYMFONY_VERSION='3.0.*'
        - php: 7.0
          env: SYMFONY_VERSION='3.1.*'
        - php: 7.0
          env: SYMFONY_VERSION='3.2.*'
        - php: hhvm
    allow_failures:
        - php: hhvm

before_install:
    - if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then phpenv config-add travis.php.ini; fi;
    - composer self-update
    - if [ "$SYMFONY_VERSION" != "" ]; then composer require --dev --no-update symfony/symfony=$SYMFONY_VERSION; fi;

install:
    - composer update --prefer-dist

script:
    - vendor/bin/phpunit
